apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-front
  labels:
    app: react-front
spec:
  selector:
    matchLabels:
      app: react-front
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
