apiVersion: v1
kind: Pod
metadata:
  name: react
  labels: 
    app: react
spec:
  containers:
  - name: react
    image: "jcrmindster/hello-mindster-react:{{ .Values.image.tag }}"
    ports:
    - containerPort: 3000
