apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: 
spec:
  selector: 
    app: nginx
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
