apiVersion: batch/v1
kind: Job
metadata:
  name: curl
spec:
  template:
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest
        command: ["curl", "<Endpoint>", "-d", "'FromK8s'"]
      restartPolicy: Never
